using NLog;
using Microsoft.AspNetCore.SignalR;
using BlazorSignalRApp.data; // Pour que AppDbContext soit reconnu
using BlazorSignalRApp.Models; // Pour que Message soit reconnu (ajuste si besoin)

namespace BlazorSignalRApp.Hubs
{
    public class ChatHub : Hub
    {
        private readonly AppDbContext _context;
        private readonly Logger _logger;

        

        public async Task SendMessage(string user, string message)
        {
           // _logger.Info($"SignalR received message from {user}: {message}");

            var newMessage = new Message
            {
                // Corrected the type mismatch by assigning a default integer value for Id
                Sender = user, // Assuming Id will be auto-generated by the database
                Content = message,
                Timestamp = DateTime.Now
            };

            //_context.Messages.Add(newMessage);
            //await _context.SaveChangesAsync();

            await Clients.All.SendAsync("ReceiveMessage", user, message);
        }
    }
}
